In [1]:
import numpy as np

In [2]:
scaler = np.array(12)

In [3]:
scaler

array(12)

In [4]:
scaler.ndim

0

#scaler is a zero dimensional tensor or vector

In [6]:
np.array([12]).ndim

1

In [7]:
np.array([[12]]).ndim

2

In [8]:
id_vector = np.array([123,22,34,57,0,])

In [9]:
id_vector

array([123,  22,  34,  57,   0])

In [11]:
id_vector.shape

(5,)

In [12]:
id_vector = np.array([[12,51,564,11,66,]])

In [13]:
id_vector.shape

(1, 5)

In [16]:
id_vector = np.array([[[15,54,364,]]],dtype = 'float')

In [17]:
id_vector.shape

(1, 1, 3)

In [18]:
id_vector

array([[[ 15.,  54., 364.]]])

In [19]:
import keras

C:\Users\Shaheer Akram\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [21]:
keras.layers.Dense('512',activation = 'relu')

output = relu(dot(W,input)+b)

data convert into tensor as input multiplied by weight and b is added y = mx +b

In [24]:
matrix = np.array([[2,3,4],[4,5,6]])

In [25]:
matrix

array([[2, 3, 4],
       [4, 5, 6]])

In [26]:
matrix*2

array([[ 4,  6,  8],
       [ 8, 10, 12]])

In [27]:
matrix1 = matrix

In [28]:
matrix2 = matrix +matrix1

In [29]:
matrix2

array([[ 4,  6,  8],
       [ 8, 10, 12]])

In [30]:
matrix*matrix2

array([[ 8, 18, 32],
       [32, 50, 72]])

In [31]:
matrix2.shape

(2, 3)

In [32]:
matrix.shape

(2, 3)

In [36]:
matrix2 = np.array([[1,2,3],[2,3,4],[5,6,8]])

In [38]:
matrix3 = matrix@matrix2

In [39]:
matrix3

array([[28, 37, 50],
       [44, 59, 80]])