In [7]:
import numpy as np
x = np.array(([[1,2,3]]))

In [11]:
type(x)
x.shape

(1, 3)

In [19]:
arr = np.arange(45)
arr = arr.reshape(3,3,5)
#reshape method

In [20]:
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [44]:
#formula array[srart:end:step,...]
x= arr[1:2:1,0:2,0:2]

In [45]:
x

array([[[15, 16],
        [20, 21]]])

In [46]:
y

array([], shape=(0, 3, 5), dtype=int32)

In [48]:
assingment = np.arange(54).reshape(6,9)
print(assingment)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]]


In [55]:
new = assingment[3:,3:]
new

array([[30, 31, 32, 33, 34, 35],
       [39, 40, 41, 42, 43, 44],
       [48, 49, 50, 51, 52, 53]])

In [60]:
ar= np.arange(27).reshape(3,3,3)

In [62]:
ar


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [64]:
ch = ar[1:2,0:1,0:1]

In [66]:
ch

array([[[9]]])

In [74]:
access = ar[1,0,0]
access

25

In [75]:
ar[1,0,0]=25

In [82]:
index = np.arange(36).reshape(6,6)
k=0

In [88]:
arr = np.arange(-2,2,0.2,dtype="float")

In [94]:
new1 = np.linspace(0.5,1.5,11)

In [97]:
print(new1[::2])

[0.5 0.7 0.9 1.1 1.3 1.5]


In [102]:
arbit = np.arange(16,dtype="float").reshape(4,4)
sec = arbit[:,1:2]

In [101]:
sec

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [104]:
arbit[0:2,0:2] = 0.21

In [106]:
arbit

array([[ 0.21,  0.21,  2.  ,  3.  ],
       [ 0.21,  0.21,  6.  ,  7.  ],
       [ 8.  ,  9.  , 10.  , 11.  ],
       [12.  , 13.  , 14.  , 15.  ]])

In [ ]:
np.sin