In [2]:
import numpy as np

In [4]:
arr = np.arange(0,27).reshape(3,3,3)

In [18]:
arr[0:1,0:1,0:2]

array([[[0, 1]]])

In [20]:
a = np.arange(0,5)


In [23]:
print(a)
(a<2)|(a>3)

[0 1 2 3 4]


array([ True,  True, False, False,  True])

In [24]:
def exp(x):
    return x<3 or x>3
np.vectorize(exp)(a)

array([ True,  True,  True, False,  True])

In [27]:
r = a<3
a[r]

array([0, 1, 2])

In [30]:
s = np.arange(25)
print(s)
#to check how many conditions are true
np.sum(s<10)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


10

In [36]:
b = np.arange(25).reshape(5,5)
y = b.flatten()
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
x = np.arange(9).reshape(3,3)
x


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
x.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [51]:
a = np.arange(9).reshape(3,3)
print(a)
b = np.arange(10,19).reshape(3,3)
print(b)
c = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [53]:
st = np.hstack((a,b,c))
print(st)

[[ 0  1  2 10 11 12  0  1  2]
 [ 3  4  5 13 14 15  3  4  5]
 [ 6  7  8 16 17 18  6  7  8]]


In [55]:
vst = np.vstack((a,b))
print(vst)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [61]:
met = np.dstack((a,b,c))

In [63]:
met2 = np.dstack((a,b,c))

In [68]:
print(met)
np.dstack(((met,met2)))

[[[ 0 10  0]
  [ 1 11  1]
  [ 2 12  2]]

 [[ 3 13  3]
  [ 4 14  4]
  [ 5 15  5]]

 [[ 6 16  6]
  [ 7 17  7]
  [ 8 18  8]]]


array([[[ 0, 10,  0,  0, 10,  0],
        [ 1, 11,  1,  1, 11,  1],
        [ 2, 12,  2,  2, 12,  2]],

       [[ 3, 13,  3,  3, 13,  3],
        [ 4, 14,  4,  4, 14,  4],
        [ 5, 15,  5,  5, 15,  5]],

       [[ 6, 16,  6,  6, 16,  6],
        [ 7, 17,  7,  7, 17,  7],
        [ 8, 18,  8,  8, 18,  8]]])

In [70]:
met.flatten()

array([ 0, 10,  0,  1, 11,  1,  2, 12,  2,  3, 13,  3,  4, 14,  4,  5, 15,
        5,  6, 16,  6,  7, 17,  7,  8, 18,  8])

In [74]:
sp = np.arange(27).reshape(3,3,3)

In [82]:
x = np.arange(10,19).reshape(3,3)
print(x)
x.min(axis=1)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


array([10, 13, 16])

In [86]:
n= x.T
n

array([[10, 13, 16],
       [11, 14, 17],
       [12, 15, 18]])

In [87]:
n.min(axis=1)

array([10, 11, 12])

In [96]:
print((x>15).all())
print((x>15).any())

False
True
