In [2]:
import numpy as np
arr = np.arange(9)

In [6]:
arr.astype(np.string_)

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8'], dtype='|S11')

In [9]:
arr[0] = "shaheer"

ValueError: invalid literal for int() with base 10: 'shaheer'

In [15]:
arr = np.array([True,False,True])
arr.astype(int)

array([1, 0, 1])

# python for data analysis book

In [17]:
#fancy indexing
name = np.array(["bob","joe","will","bob","will","joe","joe"])
data = np.random.randn(7,4)

In [18]:
data

array([[-1.5843143 , -0.1938912 , -1.52393008, -0.86296278],
       [ 0.03388755, -0.74204324, -1.37430954, -0.65991018],
       [-0.51928608,  1.36725499, -0.11754745, -0.27527397],
       [-0.58775183,  1.43040016,  0.91987991, -1.0495779 ],
       [-0.21319036, -1.49555496, -1.1485187 , -0.82426761],
       [-2.23822774,  0.03778133, -1.65541878,  0.14581225],
       [-0.93056631, -1.71057058, -0.61632401, -1.07056545]])

In [19]:
name

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [22]:
name == 'bob'

array([ True, False, False,  True, False, False, False])

In [23]:
data[name =='bob']

array([[-1.5843143 , -0.1938912 , -1.52393008, -0.86296278],
       [-0.58775183,  1.43040016,  0.91987991, -1.0495779 ]])

In [31]:
data [name != 'bob']

array([[ 0.03388755, -0.74204324, -1.37430954, -0.65991018],
       [-0.51928608,  1.36725499, -0.11754745, -0.27527397],
       [-0.21319036, -1.49555496, -1.1485187 , -0.82426761],
       [-2.23822774,  0.03778133, -1.65541878,  0.14581225],
       [-0.93056631, -1.71057058, -0.61632401, -1.07056545]])

In [32]:
new_fanc = np.arange(45).reshape(9,5)
new_fanc

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [36]:
new_fanc[[1,4]]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [38]:
data[name =='bob',2:]

array([[-1.52393008, -0.86296278],
       [ 0.91987991, -1.0495779 ]])

In [39]:
data[data<0]=0

In [40]:
data

array([[0.        , 0.        , 0.        , 0.        ],
       [0.03388755, 0.        , 0.        , 0.        ],
       [0.        , 1.36725499, 0.        , 0.        ],
       [0.        , 1.43040016, 0.91987991, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.03778133, 0.        , 0.14581225],
       [0.        , 0.        , 0.        , 0.        ]])

In [44]:
x = [1,2,3]
y = ['a','b','c']
z=zip(x,y)
list(z)

[(1, 'a'), (2, 'b'), (3, 'c')]

In [45]:
data.sum()

3.9350161739498692

In [46]:
data.max()

1.4304001623038451

In [47]:
data.min()

0.0

In [48]:
x = np.arange(12).reshape(3,4)
y = np.arange(12).reshape(4,3)

In [53]:
sq =x@y
sq
#for dot product

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])